/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Dashboard.BuildingRooms;

import Models.Buildings;
import Models.Rooms;
import Models.Users;
import Util.LocalSession;
import Util.Response;
import View.Dashboard.Dashboard;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahi
 */
public class EditRoom extends javax.swing.JPanel {

    private Dashboard parent;
    private Rooms room;

    /**
     * Creates new form EditRoom
     */
    public EditRoom(Dashboard d, Rooms r) {
        parent = d;
        room = r;
        initComponents();
        setBuildingDropdownValue();
        loadFormData();
    }

    public EditRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldRoomName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRoomRent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<Buildings>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRoomDetails = new javax.swing.JTextArea();

        jLabel1.setText("Room Floor    :");

        jLabel3.setText("Rent                 :");

        jLabel4.setText("Building           :");

        jButton1.setText("back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("save");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("clear");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<Buildings>());
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel5.setText("Details              :");

        jTextAreaRoomDetails.setColumns(20);
        jTextAreaRoomDetails.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRoomDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRoomRent, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(125, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRoomRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setBuildingDropdownValue() {
        Users loggedInUser = LocalSession.user();
        if (loggedInUser == null) {
            System.out.println("No user logged in!");
            return;
        }

        ArrayList<Buildings> buildingses = Buildings.byUserId(loggedInUser.getId());
        jComboBox1.removeAllItems();

        // Add a dummy placeholder object
        Buildings placeholder = new Buildings();
        placeholder.setBuildingName("Please select");
        placeholder.setAddress("");
        placeholder.setPaymentDetails("");
        placeholder.setUserId(loggedInUser.getId());
        placeholder.setPolicy("");
// id = 0 means it's not a real building
// (you can also add a constructor for this case)
        jComboBox1.addItem(placeholder);

        for (Buildings bc : buildingses) {
            jComboBox1.addItem(bc);  // add the object itself
        }
        // Optionally force the combo box to show the placeholder initially
        jComboBox1.setSelectedIndex(0);

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListRoom view = new ListRoom(parent);
        parent.setJContainerContent(view, "List Room");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String room_name = jTextFieldRoomName.getText();
        String room_rent_text = jTextFieldRoomRent.getText();
        String room_details = jTextAreaRoomDetails.getText();
        Buildings building = (Buildings) jComboBox1.getSelectedItem();

        // Validation
        if (room_name == null || room_name.trim().isEmpty()
                || room_rent_text == null || room_rent_text.trim().isEmpty()
                || room_details == null || room_details.trim().isEmpty()
                || building == null || building.getId() == 0) {   // check placeholder
            JOptionPane.showMessageDialog(this,
                    "All fields are required!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Check if rent is numeric
        Double room_rent;
        try {
            room_rent = Double.parseDouble(room_rent_text);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Room rent must be a valid number!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (room_rent <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Room rent must be greater than 0!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        this.room.setRoomName(room_name);
        this.room.setRoomDetails(room_details);
        this.room.setRent(room_rent);
        this.room.setBuildingId(building.getId());

        // ========== SAVE TO DATABASE ==========
        Response res = this.room.update();

        if (res.isSuccess()) {
            JOptionPane.showMessageDialog(this,
                    "Room updated successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );

            ListRoom view = new ListRoom(parent);
            parent.setJContainerContent(view, "Room list");

            // Clear fields
            jTextFieldRoomName.setText("");
            jTextFieldRoomRent.setText("");
            jTextAreaRoomDetails.setText("");
            jComboBox1.setSelectedIndex(0);

        } else {
            // Show SQL error to user
            JOptionPane.showMessageDialog(this,
                    "Failed to create Room!\n" + res.getMsg(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextFieldRoomName.setText("");
        jTextFieldRoomRent.setText("");
        jTextAreaRoomDetails.setText("");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void loadFormData() {
        if (room != null) {
            jTextFieldRoomName.setText(room.getRoomName());
            jTextAreaRoomDetails.setText(room.getRoomDetails());
            jTextFieldRoomRent.setText(Double.toString(room.getRent()));

            // Loop through combo box items
            for (int i = 0; i < jComboBox1.getItemCount(); i++) {
                Buildings b = (Buildings) jComboBox1.getItemAt(i);
                if (b.getId() == room.getBuildingId()) {
                    jComboBox1.setSelectedIndex(i); // ✅ select the matching building
                    break;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Buildings> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRoomDetails;
    private javax.swing.JTextField jTextFieldRoomName;
    private javax.swing.JTextField jTextFieldRoomRent;
    // End of variables declaration//GEN-END:variables
}
