package View.Dashboard.Building;

import Models.Buildings;
import Models.Users;
import Util.LocalSession;
import Util.Response;
import View.Dashboard.Dashboard;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Mahi
 */
public class EditBuilding extends javax.swing.JPanel {

    private Dashboard parent;

    private Buildings building;

    /**
     * Creates new form Building
     */
    public EditBuilding(Dashboard d, Buildings b) {
        parent = d;
        building = b;
        initComponents();
        LoadFormData();
    }

    /**
     * Creates new form EditBuilding
     */
    public EditBuilding() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextFieldBuildingName1 = new javax.swing.JTextField();
        jTextFieldBuldingAddress1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPaymentDetails1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPolicy1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel5.setText("Building Name    :");

        jTextFieldBuildingName1.addActionListener(this::jTextFieldBuildingName1ActionPerformed);

        jTextFieldBuldingAddress1.addActionListener(this::jTextFieldBuldingAddress1ActionPerformed);

        jLabel6.setText("Building Address :");

        jLabel7.setText("Payment Details  :");

        jLabel8.setText("Policy                   :");

        jTextAreaPolicy1.setColumns(20);
        jTextAreaPolicy1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPolicy1);

        jButton4.setText("back");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Save");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Clear");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldBuildingName1)
                                .addComponent(jTextFieldBuldingAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(jTextFieldPaymentDetails1))
                            .addGap(32, 32, 32)
                            .addComponent(jButton4))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton6)
                                .addComponent(jLabel8))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                    .addComponent(jButton5)
                                    .addGap(99, 99, 99)))))
                    .addGap(44, 44, 44)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldBuildingName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldBuldingAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPaymentDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuildingName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuildingName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuildingName1ActionPerformed

    private void jTextFieldBuldingAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuldingAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuldingAddress1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ListBuilding view = new ListBuilding(parent);
        parent.setJContainerContent(view, "Building List");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name = jTextFieldBuildingName1.getText();
        String address = jTextFieldBuldingAddress1.getText();
        String payment_details = jTextFieldPaymentDetails1.getText();
        String policy = jTextAreaPolicy1.getText();
        if (name.isEmpty() || address.isEmpty() || policy.isEmpty()
                || payment_details.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "All fields are required!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;

        }
        building.setBuildingName(name);
        building.setAddress(address);
        building.setPolicy(policy);
        building.setPaymentDetails(payment_details);

        // ========== SAVE TO DATABASE ==========
        Response res = building.update();

        if (res.isSuccess()) {
            JOptionPane.showMessageDialog(this,
                    "Building updated successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // Clear fields
            jTextFieldBuildingName1.setText("");
            jTextAreaPolicy1.setText("");
            jTextFieldBuldingAddress1.setText("");
            jTextFieldPaymentDetails1.setText("");

        } else {
            // Show SQL error to user
            JOptionPane.showMessageDialog(this,
                    "Failed to create Building!\n" + res.getMsg(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

        ListBuilding view = new ListBuilding(parent);
        parent.setJContainerContent(view, "Building List");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextFieldBuildingName1.setText("");
        jTextAreaPolicy1.setText("");
        jTextFieldBuldingAddress1.setText("");
        jTextFieldPaymentDetails1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void LoadFormData() {
        if (building != null) {
            jTextFieldBuildingName1.setText(building.getBuildingName());
            jTextFieldBuldingAddress1.setText(building.getAddress());
            jTextAreaPolicy1.setText(building.getPolicy());
            jTextFieldPaymentDetails1.setText(building.getPaymentDetails());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPolicy1;
    private javax.swing.JTextField jTextFieldBuildingName1;
    private javax.swing.JTextField jTextFieldBuldingAddress1;
    private javax.swing.JTextField jTextFieldPaymentDetails1;
    // End of variables declaration//GEN-END:variables
}
