/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Dashboard.Customer.Rooms;

import Models.Booking;
import Models.Buildings;
import Models.RoomDetails;
import Models.Users;
import Util.ActionEditor;
import Util.ActionRenderer;
import Util.LocalSession;
import View.Dashboard.Dashboard;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahi
 */
public class BookedRoomTable extends javax.swing.JPanel {

    private Dashboard parent;

    /**
     * Creates new form BookedRoomTable
     */
    public BookedRoomTable(Dashboard parent) {
        this.parent = parent;
        initComponents();
        loadTableData();
    }

    public BookedRoomTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Rent rooms");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Building Name", "Room name", "Rent", "User name", "Booking Date", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void reloadTableData() {
        loadTableData();
    }

    private void loadTableData() {
        Users loggedInUser = LocalSession.user(); // get current user
        if (loggedInUser == null) {
            System.out.println("No user logged in!");
            return;
        }
        ArrayList<RoomDetails> booking_list = new Booking().LoadBookedRoomByOwner(loggedInUser.getId());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear existing rows

        for (RoomDetails b : booking_list) {
            model.addRow(new Object[]{
                b.getBuilding().getBuildingName(),
                b.getRoom().getRoomName(),
                b.getRoom().getRent(),
                b.getUser().getUsername(),
                b.getCreatedAt(),
                b
            });
        }
        jTable1.setRowHeight(30); // sets all rows to 30 pixels high
        jTable1.getColumn("Action").setCellRenderer(new ActionRenderer(true));
        jTable1.getColumn("Action").setCellEditor(new ActionEditor(jTable1, parent, this::reloadTableData, true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
