/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Dashboard.Customer.Rooms;

import Models.Booking;
import Models.Rooms;
import Models.Users;
import Util.LocalSession;
import View.Dashboard.CustomerDashboard;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Mahi
 */
public class BookedRoom extends javax.swing.JPanel {

    CustomerDashboard parent;
    private ArrayList<Rooms> rooms;

    /**
     * Creates new form BookedRoom
     */
    public BookedRoom() {
        initComponents();
        loadRooms();
        buildCards();
    }

    public BookedRoom(CustomerDashboard parent) {
        initComponents();
        this.parent = parent;
        loadRooms();
        buildCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // ============================
    // Load rooms using your Rooms model
    // ============================
    private void loadRooms() {
        Users user = LocalSession.loadUser();
        rooms = Booking.findByUserAndStatus(user.getId(), 1); // fetch all rooms
    }

    // ============================
    // Build card UI for each room
    // ============================
    private void buildCards() {
        // Panel that stacks cards vertically
        JPanel feedPanel = new JPanel();
        feedPanel.setLayout(new BoxLayout(feedPanel, BoxLayout.Y_AXIS));

        for (Rooms room : rooms) {
            Card card = new Card(room, parent);

            // Fix width to 300, height auto
            card.setPreferredSize(new Dimension(300, card.getPreferredSize().height));
            card.setMaximumSize(new Dimension(300, Integer.MAX_VALUE));
            card.setAlignmentX(Component.CENTER_ALIGNMENT);

            feedPanel.add(card);
            feedPanel.add(Box.createRigidArea(new Dimension(0, 10))); // spacing
        }

        // Attach feedPanel to scroll pane correctly
        jScrollPane1.setViewportView(feedPanel);

        // Optional: force vertical scroll only
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
