/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Dashboard.Customer.Rooms;

import Models.Rooms;
import View.Dashboard.Customer.Building.BuildingRoomBook;
import View.Dashboard.CustomerDashboard;
import View.Dashboard.Dashboard;

/**
 *
 * @author Mahi
 */
public class Card extends javax.swing.JPanel {

    private Rooms room; // hold the room data
    CustomerDashboard parent;

    public Card(Rooms room, CustomerDashboard parent) {
        this.room = room;
        this.parent = parent;
        initComponents();
        loadData(); // populate labels with room info
    }

    public Card() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRoomName = new javax.swing.JLabel();
        jLabelRoomDetails = new javax.swing.JLabel();
        jLabelRent = new javax.swing.JLabel();
        jButtonBook = new javax.swing.JButton();

        jLabelRoomName.setText("jLabel1");

        jLabelRoomDetails.setText("jLabel1");

        jLabelRent.setText("jLabel1");

        jButtonBook.setText("jButton1");
        jButtonBook.addActionListener(this::jButtonBookActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabelRoomName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRent)
                        .addGap(81, 81, 81)
                        .addComponent(jButtonBook))
                    .addComponent(jLabelRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelRoomName)
                .addGap(18, 18, 18)
                .addComponent(jLabelRoomDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRent)
                    .addComponent(jButtonBook))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        if (room != null) {
            new BuildingRoomBook(room).setVisible(true);
            parent.dispose();
        }
    }//GEN-LAST:event_jButtonBookActionPerformed

    // ============================
    // Load room data into labels
    // ============================
    private void loadData() {
        if (room != null) {
            // Room name with icon
            jLabelRoomName.setText("🏠 " + room.getRoomName());

            // Wrap details text so it auto-breaks
            jLabelRoomDetails.setText("<html><p style='width:250px'>" + room.getRoomDetails() + "</p></html>");

            // Rent with emoji
            jLabelRent.setText("💲 Rent: $" + room.getRent());
        }

        // ============================
        // Card Styling
        // ============================
        setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
                javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15) // padding
        ));
        setBackground(new java.awt.Color(245, 245, 245));

        // Fonts
        jLabelRoomName.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        jLabelRoomDetails.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
        jLabelRent.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 14));

        // Book button styling
        jButtonBook.setText("Details");
        jButtonBook.setBackground(new java.awt.Color(0, 153, 255));
        jButtonBook.setForeground(java.awt.Color.WHITE);
        jButtonBook.setFocusPainted(false);
        jButtonBook.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));

        // Hover effect for button
        jButtonBook.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBook.setBackground(new java.awt.Color(0, 120, 200)); // darker blue
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBook.setBackground(new java.awt.Color(0, 153, 255)); // original blue
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBook;
    private javax.swing.JLabel jLabelRent;
    private javax.swing.JLabel jLabelRoomDetails;
    private javax.swing.JLabel jLabelRoomName;
    // End of variables declaration//GEN-END:variables
}
